name: PushGitlab

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with: 
        fetch-depth: 0
    - name: Push To Gitlab
      env:
       token: ${{ secrets.GITLAB_ACCESS_TOKEN }} 
       url: ${{ secrets.GITLAB_PUSH_REPO_NO_AUTH}}
       repo: ${{ secrets.GITLAB_REPO}}
      run: |
        echo Starting to push repo to gitlab
        git config user.name "Github-Actions-Bot"
        git config user.email "github@no-reply.com"
        git remote set-url origin "http://oauth2:${token}@{url}/${repo}.git"
        git push origin master

